# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/midi_project/midi_project.srcs/sources_1/ip/blk_mem_gen_y_1/blk_mem_gen_y.xci
# IP: The module: 'blk_mem_gen_y' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/midi_project/midi_project.srcs/sources_1/ip/blk_mem_gen_y_1/blk_mem_gen_y_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_y'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: o:/midi_project/midi_project.srcs/sources_1/ip/blk_mem_gen_y_1/blk_mem_gen_y.xci
# IP: The module: 'blk_mem_gen_y' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: o:/midi_project/midi_project.srcs/sources_1/ip/blk_mem_gen_y_1/blk_mem_gen_y_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_y'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
